name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  linting:
    name: Review & Lint
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: bundle install (deps)
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run SwiftLint (via Danger)
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger
